### ISSUE TITLE
notes module writeToFile() doesn't work as expected

### ISSUE THREAD

**Issue by SeanKuehl** [SeanKuehl/Forever-Note-Group-Project#16]
The problem was when setting Password the change doesn't save to file, the fix was we overwrote the existing file.  The problem was on Note.h, WriteToFile(), line 24. We found it through manual testing and debugging.

**Comment by KevinMcDanielConestoga** [comment]
In order to overwrite the existing file, the WriteToFile() private function (which uses the known file path) was made public for access during small changes like the setting of password
