### ISSUE TITLE
List Categories issue

### ISSUE THREAD

**Issue by Babywise** [SeanKuehl/Forever-Note-Group-Project#2]
In the wiki i mentioned that printCategories() function will use the categories module, however this must actually be called from the users module since the categories module will not be aware of other existing categories

**Comment by Babywise** [comment]
an addition to this is that the user module must output a  std::vector<std::string> instead of the std::string that I had before, this is because a vector holds more than one string while std::string is simply a single string

**Comment by SeanKuehl** [comment]
Ok, I've implemented the required functions as a part of my Users module.
