### ISSUE TITLE
review of my dir list code from teams

### ISSUE THREAD

**Issue by SeanKuehl** [SeanKuehl/Forever-Note-Group-Project#4]

**Comment by KevinMcDanielConestoga** [comment]
Yea that looks like it will show everything inside a directory (1 level deep), not sure if we should be looking for extensions or not

**Comment by SeanKuehl** [comment]
Assuming we always know the current directory(folder) we're working with it should be fine. Do we have a way to do that? Like adding the name of a folder onto a directory and passing that?

**Comment by KevinMcDanielConestoga** [comment]
yea the 1 level deep thing is fine, no complaint, just a comment. 
Im not sure i understand your last sentence, but for notes im making them with the extension .note. So we could ensure that the files found are in-fact notes

**Comment by SeanKuehl** [comment]
this code was deemed good and it's equivalent in the users module was integrated with success.
